apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: NodePort
  nodeport_port: 32000
  projects_persistence: true
  projects_storage_size: 5Gi
  projects_storage_access_mode: ReadWriteMany
