---
- name: Show Interface Brief on Cisco Router
  hosts: all
  gather_facts: no
  connection: network_cli
  
  vars:
    # These can be overridden in AWX job template extra variables
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_user: "{{ router_username | default('admin') }}"
    ansible_password: "{{ router_password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  tasks:
    - name: Gather router facts
      ios_facts:
        gather_subset: min
      register: router_facts
      
    - name: Display router information
      debug:
        msg: 
          - "Router: {{ ansible_host }}"
          - "Hostname: {{ router_facts.ansible_facts.ansible_net_hostname }}"
          - "IOS Version: {{ router_facts.ansible_facts.ansible_net_version }}"
          - "Model: {{ router_facts.ansible_facts.ansible_net_model }}"
      
    - name: Show interface brief
      ios_command:
        commands:
          - show ip interface brief
      register: interface_brief
      
    - name: Display interface brief output
      debug:
        var: interface_brief.stdout_lines[0]
        
    - name: Show interface status
      ios_command:
        commands:
          - show interface status
      register: interface_status
      ignore_errors: yes
      
    - name: Display interface status (if available)
      debug:
        var: interface_status.stdout_lines[0]
      when: interface_status is succeeded
      
    - name: Show running interfaces only
      ios_command:
        commands:
          - show ip interface brief | include up
      register: active_interfaces
      
    - name: Display active interfaces
      debug:
        msg: "Active Interfaces: {{ interface_brief.stdout[0] | regex_findall('(\\S+)\\s+\\S+\\s+\\S+\\s+up\\s+up') }}"
      
    - name: Create summary report
      debug:
        msg:
          - "=== INTERFACE SUMMARY FOR {{ ansible_host }} ==="
          - "Router Model: {{ router_facts.ansible_facts.ansible_net_model | default('Unknown') }}"
          - "IOS Version: {{ router_facts.ansible_facts.ansible_net_version | default('Unknown') }}"
          - "Hostname: {{ router_facts.ansible_facts.ansible_net_hostname | default('Unknown') }}"
          - ""
          - "=== INTERFACE BRIEF ==="
          - "{{ interface_brief.stdout[0] }}"