---
- name: Retrieve Dialer0 interface IP address
  hosts: all
  gather_facts: false
  tasks:
    - name: Test basic show command
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: basic_output
      
    - name: Debug basic output
      ansible.builtin.debug:
        msg: |
          === BASIC SHOW IP INT BRIEF OUTPUT ===
          Success: {{ basic_output is succeeded }}
          Output length: {{ basic_output.stdout[0] | default('') | length }}
          Raw output: "{{ basic_output.stdout[0] | default('NO OUTPUT') }}"
      
    - name: Search for Dialer0 in output
      ansible.builtin.set_fact:
        dialer0_line: "{{ basic_output.stdout[0] | regex_search('Dialer0.*') }}"
        dialer0_ip: "{{ basic_output.stdout[0] | regex_search('Dialer0\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+)', '\\1') | first }}"
      when: basic_output.stdout[0] is defined and 'Dialer0' in basic_output.stdout[0]
      
    - name: Display results
      ansible.builtin.debug:
        msg: |
          === DIALER0 RESULTS ===
          Found Dialer0: {{ 'Dialer0' in (basic_output.stdout[0] | default('')) }}
          Dialer0 Line: "{{ dialer0_line | default('Not found') }}"
          Dialer0 IP: {{ dialer0_ip | default('Not found') }}
          
    - name: Show success message
      ansible.builtin.debug:
        msg: "✅ SUCCESS: Dialer0 IP address is {{ dialer0_ip }}"
      when: dialer0_ip is defined