---
- name: Quick Router Running Config Retrieval  
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Get router basic info
      cisco.ios.ios_command:
        commands:
          - show version | include hostname|IOS|uptime
      register: basic_info

    - name: Show router basic info
      debug:
        msg: |
          ==================== ROUTER INFO ====================
          {{ basic_info.stdout[0] }}
          =====================================================

    - name: Get complete running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Display running configuration
      debug:
        msg: |
          ==================== COMPLETE RUNNING CONFIG ====================
          {{ running_config.stdout[0] }}
          ==================================================================

    - name: Get interface status
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: interface_status

    - name: Show interface status
      debug:
        msg: |
          ==================== INTERFACE STATUS ====================
          {{ interface_status.stdout[0] }}
          ==========================================================

    - name: Create summary for job artifacts
      set_fact:
        router_config_summary:
          config_retrieved: true
          config_lines: "{{ running_config.stdout[0].split('\n') | length }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          hostname_from_config: "{{ running_config.stdout[0] | regex_search('hostname (.+)', '\\1') | first | default('Unknown') }}"

    - name: Final summary
      debug:
        msg:
          - "==================== SUMMARY ===================="
          - "✅ Configuration Retrieved Successfully"
          - "📝 Total Config Lines: {{ router_config_summary.config_lines }}"
          - "🏷️  Hostname: {{ router_config_summary.hostname_from_config }}"
          - "⏰ Retrieved: {{ router_config_summary.timestamp }}"
          - "=================================================="