---
- name: Test Palo Alto VM Connection (Direct API)
  hosts: all
  gather_facts: no
  vars:
    panos_ip: "{{ ansible_host | default('192.168.0.100') }}"
    panos_username: "{{ panos_username | default('admin') }}"
    panos_password: "{{ panos_password | default('Lin@226659') }}"
    panos_api_key: "{{ panos_api_key | default('') }}"
    
  tasks:
    - name: Test basic connectivity to Palo Alto
      uri:
        url: "https://{{ panos_ip }}/api/"
        method: GET
        validate_certs: no
        timeout: 30
        status_code: [200, 400, 403]
      register: connectivity_test
      
    - name: Show connectivity result
      debug:
        msg: "Palo Alto VM at {{ panos_ip }} is reachable (HTTP {{ connectivity_test.status }})"
        
    - name: Get system information using API key
      uri:
        url: "https://{{ panos_ip }}/api/"
        method: GET
        validate_certs: no
        timeout: 30
        body_format: form-urlencoded
        body:
          type: op
          cmd: "<show><system><info></info></system></show>"
          key: "{{ panos_api_key }}"
      register: system_info
      when: panos_api_key != ""
      
    - name: Display system information
      debug:
        msg: "System Info Response: {{ system_info.content }}"
      when: panos_api_key != "" and system_info is defined
      
    - name: Test with username/password if API key not available
      uri:
        url: "https://{{ panos_ip }}/api/"
        method: GET
        validate_certs: no
        timeout: 30
        body_format: form-urlencoded
        body:
          type: op
          cmd: "<show><system><info></info></system></show>"
          user: "{{ panos_username }}"
          password: "{{ panos_password }}"
      register: system_info_pwd
      when: panos_api_key == ""
      
    - name: Display system information (username/password)
      debug:
        msg: "System Info Response: {{ system_info_pwd.content }}"
      when: panos_api_key == "" and system_info_pwd is defined