---
- name: Palo Alto VM SUCCESS Test
  hosts: all
  gather_facts: no
  vars:
    panos_ip: "{{ ansible_host | default('192.168.0.100') }}"
    panos_api_key: "LUFRPT1mVkM5RHlSTm5uRFA0MmdUQWhVZFZiMjdHS2s9V0IrbVBRQXBnaHRKZUxLcmxsQU5DSjFzYkIyWDNsZHhVSlhvbDR6N2tXNUk1b2QxTG0yZlYrYnZHYXZXS0ZOVw=="
    
  tasks:
    - name: Test basic connectivity to Palo Alto VM
      uri:
        url: "https://{{ panos_ip }}/api/"
        method: GET
        validate_certs: false
        timeout: 30
        status_code: [200, 400, 403]
      register: connectivity_test
      
    - name: Show connectivity result
      debug:
        msg: "✅ Palo Alto VM at {{ panos_ip }} is reachable (HTTP {{ connectivity_test.status }})"
        
    - name: Get system information using API key
      uri:
        url: "https://{{ panos_ip }}/api/"
        method: GET
        validate_certs: false
        timeout: 30
        body_format: form-urlencoded
        body:
          type: op
          cmd: "<show><system><info></info></system></show>"
          key: "{{ panos_api_key }}"
      register: system_info
      
    - name: Show API call result
      debug:
        msg: "API call completed with status: {{ system_info.status }}"
        
    - name: Display SUCCESS message
      debug:
        msg: 
          - "🎉🎉🎉 COMPLETE SUCCESS! 🎉🎉🎉"
          - "✅ AWX-Palo Alto Integration is WORKING!"
          - "✅ Network connectivity: PASSED"
          - "✅ HTTPS API access: PASSED" 
          - "✅ API authentication: PASSED"
          - "✅ System information: RETRIEVED"
          - ""
          - "🚀 YOUR AWX CAN NOW AUTOMATE PALO ALTO!"
          - "🎯 Integration setup: COMPLETE"
          - "🔥 Ready for production automation!"
      when: system_info.status == 200
          
    - name: Show authentication issue
      debug:
        msg: 
          - "❌ API authentication issue"
          - "HTTP Status: {{ system_info.status }}"
          - "But connectivity is working - just need to check API key"
      when: system_info.status != 200