---
- name: Test Local Palo Alto VM Connection
  hosts: local-palo-vm
  gather_facts: false
  connection: local
  vars:
    # Actual credentials for local Palo Alto VM
    panos_username: "admin"
    panos_password: "Lin@226659"

  tasks:
    - name: Test basic connectivity
      paloaltonetworks.panos.panos_op:
        ip_address: "{{ panos_ip }}"
        username: "{{ panos_username }}"
        password: "{{ panos_password }}"
        cmd: "show system info"
      register: system_info

    - name: Display system information
      ansible.builtin.debug:
        msg: |
          ✅ SUCCESS: Connected to Palo Alto VM!
          System Info: {{ system_info.stdout_lines | join('\n') }}